---
- name: Crear usuario en Windows Server 2016
  hosts: Router
  tasks:
    - name: Crear usuario
      win_user:
        name: monica
        password: OracleRedsoft2022#
        state: present
        groups: Administrators  # Opcional: Agregar al grupo Administradores u otro grupo necesario
      become: yes
