---
- name: Ejecutar consulta en SQL Server
  hosts: all
  gather_facts: no
  vars:
    mssql_login_user: "Administrator"
    mssql_login_password: "OracleRedsoft2022#"
    mssql_host: "WIN-K5QJEA01EJE"
    mssql_port: "49675"  # El puerto predeterminado es 1433
    sql_query: "SELECT * FROM Productos"
  tasks:
    - name: Ejecutar consulta SQL
      community.general.mssql_script:
        login_user: "{{ mssql_login_user }}"
        login_password: "{{ mssql_login_password }}"
        login_host: "{{ mssql_host }}"
        login_port: "{{ mssql_port }}"
        db: "Productos"
        script: "{{ sql_query }}"
      register: result

    - name: Mostrar resultado
      debug:
        var: result
