---
- name: Ejecutar consulta en SQL Server
  hosts: all
  gather_facts: no
  vars:
    sql_query: "SELECT * FROM dbo.Productos"
  tasks:
    - name: Ejecutar consulta SQL con PowerShell
      win_shell: |
        $SqlConnection = New-Object System.Data.SqlClient.SqlConnection
        $SqlConnection.ConnectionString = "Server={{ mssql_host }},{{ mssql_port }};Database=Restaurante;User Id={{ mssql_login_user }};Password={{ mssql_login_password }};"
        $SqlCmd = $SqlConnection.CreateCommand()
        $SqlCmd.CommandText = "{{ sql_query }}"
        $SqlAdapter = New-Object System.Data.SqlClient.SqlDataAdapter
        $SqlAdapter.SelectCommand = $SqlCmd
        $DataSet = New-Object System.Data.DataSet
        $SqlAdapter.Fill($DataSet)
        $DataSet.Tables[0] | Format-Table -AutoSize | Out-String
      register: result
      
    - name: Mostrar resultado
      debug:
        var: result.stdout_lines
