---
- name: Ejecutar Backup de Base de Datos en SQL Server
  hosts: sqlserver
  gather_facts: no
  tasks:
    - name: Ejecutar Backup
      win_shell: |
        $ConnectionString = "Server={{ mssql_host }},{{ mssql_port }};Database={{ db }};User Id={{ mssql_login_user }};Password={{ mssql_login_password }};"
        $BackupPath = "C:\Ruta\donde\guardar\el\respaldo.bak"
        $Query = "BACKUP DATABASE Restaurante TO DISK='$BackupPath' WITH FORMAT, INIT;"
        Invoke-Sqlcmd -ConnectionString $ConnectionString -Query $Query
