---
- name: Crear carpeta compartida en Windows
  hosts: 192.168.72.3
  gather_facts: false
  tasks:
    - name: Crear carpeta en el escritorio
      win_file:
        path: "C:\\Users\\Administrator\\Desktop\\NuevaCarpeta8"  # Ruta de la nueva carpeta
        register: carpeta_creada
        state: directory
        
    - name: Add secret share
      ansible.windows.win_share:
        name: internal5
        description: top secret share
        path: C:\Users\Administrator\Desktop\NuevaCarpeta8
        list: false
        full: Administrators
