---
- name: Crear carpeta compartida en Windows
  hosts: 192.168.72.3
  gather_facts: false
  tasks:
    - name: Crear carpeta en el escritorio
      win_file:
        path: "{{path_nueva}}"  # Ruta de la nueva carpeta
        register: carpeta_creada
        state: directory
        
    - name: Agregar carpeta compartida
      ansible.windows.win_share:
        name: "{{nombre_carmpeta_compartir}}"
        description: top secret share
        path: "{{path_nueva}}"
        list: false
        full: Administrators
