---
- name: Crear carpeta compartida en Windows
  hosts: all
  gather_facts: false
  tasks:
    - name: Crear carpeta en el escritorio
      win_file:
        path: "C:\\Users\\Administrator\\Desktop\\NuevaCarpeta5"  # Ruta de la nueva carpeta
        register: carpeta_creada
        state: directory
        
    - name: Add secret share
      ansible.windows.win_share:
        name: internal
        description: top secret share
        path: C:\shares\internal
        list: false
        full: Administrators,CEO
        read: HR-Global
