---
- hosts: all
  gather_facts: false
 
  vars:
    sql_query: "SELECT * FROM Productos"
    
  tasks:
  - name: execute SQL
    community.general.mssql_script:
      login_user: "{{ mssql_login_user }}"
      login_password: "{{ mssql_login_password }}"
      login_host: "{{ mssql_host }}"
      login_port: "{{ mssql_port }}"
      db: "Restarurante"
      script: "{{ sql_query }}"
