---
- hosts: all
  gather_facts: false
 
  vars:
    sql_query: "SELECT * FROM Productos"
 
  tasks:
  - name: execute SQL
    community.general.mssql_script:
      login_user: "{{ Administrator }}"
      login_password: "{{ OracleRedsoft2022# }}"
      login_host: "{{ WIN-K5QJEA01EJE }}"
      login_port: "{{ 49675 }}"
      db: "Productos"
      script: "{{ sql_query }}"
