---
- name: Copiar archivo a carpeta en Windows
  hosts: windowsDC
  gather_facts: no

  tasks:
    - name: Copiar archivo
      win_copy:
        src: "{{origen}}"
        dest: "{{destino}}"
        remote_src: true
      register: resultado_copia
      

    - name: Imprimir resultado de la copia
      debug:
        var: resultado_copia
