---
- name: Mover archivo a Windows Server
  hosts: all   # Cambia esto al grupo o nombre de host de tu servidor Windows
  gather_facts: no

  tasks:
    - name: Copiar archivo desde AWX a Windows Server
      win_copy:
        src: /home/awx/pruebas.json  # Ruta completa del archivo en el servidor AWX
        dest: C:\Users\Administrator\Desktop\     
