---
- name: Copiar archivo desde Linux a Windows
  hosts: all
  gather_facts: no

  tasks:
    - name: Copiar archivo desde Linux a Windows
      win_copy:
        src: "scp://usuario_linux@192.168.72.50:/home/administrator/hol.json"  # Ruta completa del archivo en el servidor Linux
        dest: "C:\\Users\\Administrator\\Desktop\\"
