---
- name: Ejecutar comando en servidor remoto y guardar salida en localhost
  hosts: all  # Reemplaza con el nombre o grupo de tu servidor remoto
  gather_facts: no

  tasks:
    - name: Ejecutar el comando y obtener salida
      shell: hostname  # Ejemplo de comando que deseas ejecutar en el servidor remoto
      register: command_output

    - name: Mostrar la salida del comando
      debug:
        var: command_output.stdout

- name: Guardar la salida en localhost
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Guardar la salida en un archivo local
      copy:
        content: "{{ hostvars['tu_servidor_remoto']['command_output']['stdout'] }}"
        dest: /pruebas/command_output.txt
