---
- name: Crear carpeta en Windows Server
  hosts: all
  gather_facts: yes

  tasks:
    - name: Crear carpeta en el escritorio
      win_file:
        path: "C:\\Users\\Administrator\\Desktop\\NuevaCarpeta"  # Ruta de la nueva carpeta
        state: directory
  tasks:
    - name: Obtener información de discos
      win_disk_facts:

    - name: Mostrar información de discos
      debug:
        var: ansible_facts.disk
