---
- name: Crear carpeta en Windows Server
  hosts: all
  gather_facts: yes

  tasks:
    - name: Crear carpeta en el escritorio
      win_file:
        path: "C:\\Users\\Administrator\\Desktop\\NuevaCarpeta"  # Ruta de la nueva carpeta
        state: directory
  tasks:
    - name: Obtener información de espacio disponible en discos
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object Name, Used, Free, Size
      register: disk_space_info

    - name: Mostrar información de espacio disponible en discos
      debug:
        var: disk_space_info.stdout_lines
