---
- name: Descargar archivo desde servidor Ubuntu a Ansible Controller
  hosts: all  # Cambia esto al grupo o dirección IP de tu servidor Ubuntu
  gather_facts: no

  tasks:
    - name: Descargar archivo desde servidor Ubuntu
      fetch:
        src: "/home/Administrator/pruebas.json"  # Ruta completa del archivo en el servidor Ubuntu
        dest: "/tmp/" 
