---
- name: Main Playbook
  hosts: all
  vars:
    condition: "a"  # Esta variable podría provenir de un archivo de inventario, una variable de entorno, etc.
  tasks:
    - name: Incluir playbook A si la condición es 'a'
      include_playbook: playbook_a.yml
      when: condition == "a"

    - name: Incluir playbook B si la condición es 'b'
      include_playbook: playbook_b.yml
      when: condition == "b"
