---
- name: Leer contenido del archivo y establecer variable
  hosts: localhost
#  vars:
#    run: "pruebas.k3s"
    
  tasks:
    - name: Leer contenido del archivo nodok3_hostname.txt
      set_fact:
        nodo_hostname: "{{ lookup('file', '/pruebas/nodok3_hostname.txt') }}"
    - name: Mostrar valor de nodo_hostname para verificación
      debug:
        var: nodo_hostname
        
- import_playbook: jsondes.yaml
  when: run == "Disabled" and nodo_hostname == "Disabled"
- import_playbook: archivolocal.yaml
  when: run == "pruebas.k3s" and nodo_hostname == "pruebas.k3s"
