---
- name: Playbook Principal
  hosts: localhost
  gather_facts: false
  vars:
    condition: "a"  # Cambia esta variable para probar diferentes condiciones

  tasks:
    - name: Incluir playbook A si la condición es 'a'
      include_tasks: playbook_a.yaml
      when: condition == "a"

    - name: Incluir playbook B si la condición es 'b'
      include_tasks: playbook_b.yaml
      when: condition == "b"
