---
- name: Incluir playbook
  import_playbook: jsondes.yaml
  
- name: Playbook Principal
  hosts: localhost
  gather_facts: false
  vars:
    condition: "a"  # Cambia esta variable para probar diferentes condiciones

  tasks:
    - name: Incluir playbook a si la condición es 'b'    
      include_tasks: jsondes.yaml
      when: condition == "a"

    - name: Incluir playbook B si la condición es 'b'
      include_tasks: pruebas.yaml
      when: condition == "b"
