---
- name: Leer contenido del archivo y establecer variable
  hosts: localhost
  tasks:
    - name: Leer contenido del archivo nodok3_hostname.txt
      set_fact:
        nodo_hostname: "{{ lookup('file', '/pruebas/nodok3_hostname.txt') }}"
        
- import_playbook: jsondes.yaml
  when: run == nodo_hostname
- import_playbook: archivolocal.yaml
  when: run == 'nodo_hostname'
