---
- name: Listar grupos en Windows Server
  hosts: all
  tasks:
    - name: Obtener información de grupos
      win_shell: Get-LocalGroup
      register: group_info

    - name: Mostrar grupos
      debug:
        var: group_info.stdout_lines
