---
- name: Configurar y verificar interfaz de red en Windows
  hosts: windowsDC
  gather_facts: no
  tasks:
    - name: Habilitar interfaz de red
      win_shell: Enable-NetAdapter -Name "Ethernet 2" -Confirm:$false

    - name: Configurar IP en interfaz de red
      win_shell: New-NetIPAddress -InterfaceAlias "Ethernet 2" -IPAddress 192.168.43.1 -PrefixLength 24 -DefaultGateway 192.168.43.1

    - name: Verificar disponibilidad de la interfaz
      win_shell: Test-Connection -ComputerName 192.168.43.1 -Count 1
      register: ping_result

    - name: Levantar interfaz si no está disponible
      when: "ping_result.rc -ne 0"
      win_shell: Enable-NetAdapter -Name "NombreInterfaz" -Confirm:$false
