---
- name: Obtener el hostname y guardarlo en un archivo local
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtener el hostname del servidor remoto
      command: hostname
      register: hostname_output

    - name: Mostrar el hostname en la salida
      debug:
        var: hostname_output.stdout

    - name: Guardar el hostname en un archivo local
      local_action:
        module: copy
        content: "{{ hostname_output.stdout }}"
        dest: "/pruebas/{{ inventory_hostname }}_hostname.txt"
