---
- name: Obtener el hostname y guardarlo en un archivo local
  hosts: all
  gather_facts: no
  tasks:
    - name: Obtener el hostname del servidor remoto
      command: "{{ comando }}"
      register: hostname_output

    - name: Mostrar el hostname en la salida
      debug:
        var: hostname_output.stdout

    - name: Guardar el hostname en un archivo local
      local_action:
        module: copy
        content: "{{ hostname_output.stdout }}"
        dest: "/carpeta1/{{ inventory_hostname }}_hostname.txt"
        
- name: Copiar archivo en localhost
  hosts: localhost
  tasks:
    - name: Copiar archivo de una carpeta a otra
      copy:
        src: /pruebas/pavvasbposqldb01_hostname.txt
        dest: /carpeta1/pavvasbposqldb01_hostname.txt
