---
- hosts: 192.168.73.236
  become: true
  tasks:
    - name: Buscar el archivo en la dirección especificada
      find:
        paths: "/home/awx/Desktop"
        patterns: "hola.txt"
      register: resultado_busqueda

- hosts: 192.168.73.248
  become: true
  tasks:
    - name: Crear la carpeta de destino si no existe
      file:
        path: "/home/awx/Desktop"
        state: directory

    - name: Copiar el archivo desde 192.12.23.1 a 192.12.23.2
      copy:
        src: "/home/awx/Desktop/hola.txt"
        dest: "/home/awx/Desktop/"
