---
- name: SSH into a server and run commands on Cisco device
  hosts: all
  gather_facts: no
  tasks:
    - name: SSH into Cisco device and show version
      expect:
        command: ssh red@192.168.73.71
        responses:
          'Password:': "{{ pass }}\n"
          '.*#': 'show version\n'
        timeout: 30
        echo: true
      register: ssh_login

    - name: Display version output
      debug:
        var: ssh_login.stdout
