---
- name: Ejecutar comando SSH con Ansible
  hosts: routers
  gather_facts: no
  tasks:
    - name: Ejecutar comando SSH
      expect:
        command: ssh red@{{ ansible_host }} "show version"
        responses:
          Are you sure you want to continue connecting (yes/no/[fingerprint])? : "yes\n"
          Password: "alvis"
