---
- name: Ejecutar comando SSH con Ansible
  hosts: tu_host_remoto
  gather_facts: no
  tasks:
    - name: Ejecutar comando SSH
      expect:
        command: ssh red@{{ ansible_host }} "show version"
        responses:
          Password: "alvis"
