---
- name: Ejecutar show version en routers Cisco sin módulos específicos
  hosts: routers
  gather_facts: no

  tasks:
    - name: Ejecutar script expect para show version
      command: >
        /home/awx/sc.sh {{ ip }} {{ usuario }} {{ contraseña }}
      register: output

    - name: Mostrar salida del comando
      debug:
        var: output.stdout
