---
- name: Ejecutar script en el servidor remoto
  hosts: routers
  gather_facts: no

  tasks:
    - name: Ejecutar comando en el servidor remoto
      shell: /home/awx/sc.sh 192.168.73.71 red 123456
      register: command_output

    - debug:
        var: command_output.stdout
