---
- name: Crear carpeta compartida en Windows
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Copy a single file
      win_copy:
        src: /home/awx/pruebas.json
        dest: C:\pruebas\
