---
- name: Copiar archivo a máquina remota
  hosts: all
  become: true  # Si es necesario obtener privilegios de superusuario (sudo)

  tasks:
    - name: Copiar archivo desde el host local a la máquina remota
      ansible.builtin.copy:
        src: /tmp/hola.txt  # Ruta del archivo en el host local
        dest: /home/awx/Desktop/
      delegate_to: 192.168.73.247
