---
- name: Comprobar y reiniciar un servicio
  hosts: all
  vars:
  tasks:
    - name: Obtener el estado actual del servicio
      win_shell: Get-Service -Name {{ service_name }} | Select-Object -ExpandProperty Status
      register: service_status

    - name: Definir variable para el estado del servicio
      set_fact:
        service_state: "{{ service_status.stdout.strip() }}"

    - name: Reiniciar el servicio si está detenido
      win_shell: Restart-Service -Name {{ service_name }}
      when: service_state == 'Stopped'
