---
- name: Comprobar y reiniciar un servicio
  hosts: all
    tasks:
    - name: Comprobar y reiniciar servicios
      win_shell: |
        $services = {{ service_names | to_json }}
        foreach ($service in $services) {
          $status = Get-Service -Name $service | Select-Object -ExpandProperty Status
          if ($status -eq 'Stopped') {
            Restart-Service -Name $service
          }
        }
      run_once: true
