---
- name: Comprobar y reiniciar un servicio
  hosts: all
  tasks:
    - name: Comprobar y reiniciar servicios
      service_facts:
        gather_subset: all
      register: services

    - name: Reiniciar servicios si están detenidos
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ service_names }}"
      when: "'{{ item }}' in services.services"
